name: Check Kubernetes Files

on:
  push:
    branches:
      - main
env:
  PROJECT_ID: github-action-393418
  PROJECT_NUMBER: 168241442549
  
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    #
    # Authenticate to Google Cloud using workload identity federation
    #
    - id: 'auth'
      name: 'Obtain access token by using workload identity federation'
      uses: 'google-github-actions/auth@v0'
      with:
        create_credentials_file: true
        token_format: access_token
        workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
        service_account: github-actions-workflow@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyYAML google-cloud-bigquery pandas ghapi

    - name: Process files
      run: python .github/workflows/main.py
      env:
        GOOGLE_APPLICATION_CREDENTIALS:  ${{ steps.auth.outputs.access_token }} 
